name: deploy-new-arrival-notifier
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - new-arrival-notifier/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: node --version # DEBUG
    - name: Build
      run: |
        cd new-arrival-notifier
        npm install
        zip -r lambda_function.zip .
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ vars.AWS_OIDC_ROLE_ARN }}
    - name: Upload to S3
      run: aws s3 cp new-arrival-notifier/lambda_function.zip ${{ vars.S3_BUCKET }}/garland-new-arrival-notifier/lambda_function.zip
